project:
  tag: max-pro
  stack-base-name: max-aldunate-pro

aws:
  profile-user: testuser
  aws-region: eu-west-1
  preserve-config-output-file: false

dir:
  base: ..\
  output: aws\outputs
  stacks: aws\stacks
  apis: api\src

packages-deploy-bucket:
  stackName: 01-prerequisites
  outputKey: DeployPackagesBucketName
  swagger-file-param-name: SwaggerS3File

stacks:
  - name: 01-prerequisites
    type: NoPackage
    skip: false
    parameters-source:
      - name: AppName
        value: max-aldunate-pro

  - name: 02-cognito
    type: Package
    skip: false
    parameters-source:

  - name: course
    type: Api
    skip: false
    parameters-source:
  #  stackName:
  #  outputKey:
