project:
  tag: max-pro
  stack-base-name: max-aldunate-pro

aws:
  profile-user: testuser
  aws-region: eu-west-1    

dir:
  base: ..\
  output: aws\outputs
  stacks: aws\stacks
  apis: api\src

packages-deploy-bucket:
  stackName: 01-prerequisites
  outputKey: DeployPackagesBucketName

packages-artifacts-bucket:
  stackName: 01-prerequisites
  outputKey: ArtifactsBucketName

stacks:
  - name: 01-prerequisites
    type: NoPackage
    parameters-source:
      - name: AppName
        value: max-aldunate-pro

  - name: 02-cognito
    type: Package
    parameters-source:

  - name: course
    type: Api
    parameters-source:
  #  stackName:
  #  outputKey:
