AWSTemplateFormatVersion: '2010-09-09'
Description: Max Aldunate Pro Angular. Continuous integration mechanism
Parameters:
  TagProject:
    Type: String
    Description: "Tagging for the stack and its resources"
  WebsiteBucketName:
    Type: String
    Description: "bucket associated with hosted zone in route 53"
Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref WebsiteBucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html  
      Tags:
        -
         Key: "Project"
         Value: !Ref TagProject 
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['', [!Ref WebsiteBucketName,"-artifacts"]]
      Tags:
        -
         Key: "Project"
         Value: !Ref TagProject 

Outputs:
  ArtifactsBucketName:
    Value: !Ref ArtifactsBucket
    Description: The bucket name for deployed artifacts
  WebsiteBucketName:
    Value: !Ref WebsiteBucket
    Description: The bucket name of our website bucket
  WebsiteURL:
    Value: !GetAtt [WebsiteBucket, WebsiteURL]
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join ['', ['https://', !GetAtt [WebsiteBucket, DomainName]]]
    Description: Name of S3 bucket to hold website content