AWSTemplateFormatVersion: '2010-09-09'
Description: Max Aldunate Pro Angular. Stack with prerequisites
Parameters:
  TagProject:
    Type: String
    Description: "Tagging for the stack and its resources"
  AppName:
    Type: String
    Description: "App name, base for many names"
Resources:

  DeployPackagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['', [!Ref AppName,"-deploy-packages"]]
      Tags:
        -
         Key: "Project"
         Value: !Ref TagProject 

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['', [!Ref AppName,"-website"]]
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html  
      Tags:
        -
         Key: "Project"
         Value: !Ref TagProject

Outputs:
  DeployPackagesBucketName:
    Value: !Ref DeployPackagesBucket
    Description: The bucket name to deploy packages

  WebsiteBucketName:
    Value: !Ref WebsiteBucket
    Description: The bucket name to deploy packages

  WebsiteURL:
    Value: !GetAtt [WebsiteBucket, WebsiteURL]
    Description: URL for website hosted on S3

  WebsiteSecureURL:
    Value: !Join ['', ['https://', !GetAtt [WebsiteBucket, DomainName]]]
    Description: Name of S3 bucket to hold website content